spring:
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168

zuul:
  rsa-filter:
    exclude:
    - e-auth-tokens

  sensitiveHeaders:
#  sensitive-headers: Cookie,Set-Cookie,Authorization
#  ignore-security-headers: false
  prefix: /api/v1
  ignoredServices: '*'

  routes:
    e-auth-tokens:
      path: /auth/signin
      url: http://auth:9011
      stripPrefix: false

    e-auth-refresh:
      path: /auth/refresh
      url: http://auth:9011
      stripPrefix: false

    e-operation:
      path: /operation/**
      serviceId: e-operation
      stripPrefix: false

    orchestrator:
      path: /**
      serviceId: orchestrator
      stripPrefix: false

#    hello:
#      path: /hello/**
#      serviceId: HelloService
#      url: http://example.com/hello
#      stripPrefix: true


#**************************************
# For custom address of service E-AUTH
#**************************************
ribbon:
  eureka:
   enabled: false
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  ReadTimeout: 10000
  ConnectTimeout: 10000

E-AUTH:
  ribbon:
    listOfServers: auth:9011
#**************************************

feign:
  hystrix:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          #          strategy: SEMAPHORE
          #          semaphore:
          #            maxConcurrentRequests: 100000 # basically 'unlimited'
          #          strategy: THREAD
          thread:
            timeoutInMilliseconds: 25000
        timeout:
          enabled: false
      circuitBreaker:
        enabled: false
      fallback:
        enabled: false

        #hystrix:
        #  command:
        #    default:
        #      circuitBreaker:
        #        enabled: false

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 1000000