spring:
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168

zuul:
  filters:
    exclude:
    - hello

  sensitiveHeaders:
#  sensitive-headers: Cookie,Set-Cookie,Authorization
#  ignore-security-headers: false
#  prefix: /api
  ignoredServices: '*'

  routes:
    hello:
      path: /hello/**
#      serviceId: HelloService
      url: http://example.com/hello
      stripPrefix: true

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://eureka-peer-1:8801/eureka/,http://eureka-peer-2:8802/eureka/

jwt:
  public-key: |
             -----BEGIN PUBLIC KEY-----

             -----END PUBLIC KEY-----


#hello:
#  ribbon:
#    ReadTimeout: 10

#hystrix:
#  command:
#    hello:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5